# Generated by Django 4.2.2 on 2023-08-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0003_alter_advertisement_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='auction',
            field=models.BooleanField(help_text='отметьте, если торг уместен', verbose_name='торг'),
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
