# Generated by Django 4.2.2 on 2023-08-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0008_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
