# Generated by Django 4.2.2 on 2023-08-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0010_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
