# Generated by Django 4.2.2 on 2023-08-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0014_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Объявления'},
        ),
    ]
